name: Deploy Voila App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install voila jupyter
      
      - name: Deploy to GitHub Pages
        run: |
          voila interactive_analysis.ipynb --no-browser --port=8000 &
          npx http-server --port 8000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
