name: Deploy Voila App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install voila jupyter

      - name: Run Voila
        run: |
          PORT=$(shuf -i 2000-65000 -n 1)
          voila --port=$PORT --no-browser interactive_analysis.ipynb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
